// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Endpoint extends pulumi.CustomResource {
    /**
     * Get an existing Endpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointState, opts?: pulumi.CustomResourceOptions): Endpoint {
        return new Endpoint(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'neon:index/endpoint:Endpoint';

    /**
     * Returns true if the given object is an instance of Endpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Endpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Endpoint.__pulumiType;
    }

    /**
     * Branch the endpoint belongs to.
     */
    public readonly branchId!: pulumi.Output<string>;
    /**
     * Provisioner of the endpoint.
     */
    public /*out*/ readonly computeProvisioner!: pulumi.Output<string>;
    /**
     * Host of the endpoint.
     */
    public /*out*/ readonly host!: pulumi.Output<string>;
    /**
     * Maximum number of compute units for the endpoint. **Default** `0.25`.
     */
    public readonly maxCu!: pulumi.Output<number>;
    /**
     * Minimum number of compute units for the endpoint. **Default** `0.25`.
     */
    public readonly minCu!: pulumi.Output<number>;
    /**
     * Project the endpoint belongs to.
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * Suspend timeout of the endpoint. **Default** `0`.
     */
    public readonly suspendTimeout!: pulumi.Output<number>;
    /**
     * Type of the endpoint.
     */
    public /*out*/ readonly type!: pulumi.Output<string>;

    /**
     * Create a Endpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointArgs | EndpointState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointState | undefined;
            resourceInputs["branchId"] = state ? state.branchId : undefined;
            resourceInputs["computeProvisioner"] = state ? state.computeProvisioner : undefined;
            resourceInputs["host"] = state ? state.host : undefined;
            resourceInputs["maxCu"] = state ? state.maxCu : undefined;
            resourceInputs["minCu"] = state ? state.minCu : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["suspendTimeout"] = state ? state.suspendTimeout : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as EndpointArgs | undefined;
            if ((!args || args.branchId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'branchId'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["branchId"] = args ? args.branchId : undefined;
            resourceInputs["maxCu"] = args ? args.maxCu : undefined;
            resourceInputs["minCu"] = args ? args.minCu : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["suspendTimeout"] = args ? args.suspendTimeout : undefined;
            resourceInputs["computeProvisioner"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Endpoint.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Endpoint resources.
 */
export interface EndpointState {
    /**
     * Branch the endpoint belongs to.
     */
    branchId?: pulumi.Input<string>;
    /**
     * Provisioner of the endpoint.
     */
    computeProvisioner?: pulumi.Input<string>;
    /**
     * Host of the endpoint.
     */
    host?: pulumi.Input<string>;
    /**
     * Maximum number of compute units for the endpoint. **Default** `0.25`.
     */
    maxCu?: pulumi.Input<number>;
    /**
     * Minimum number of compute units for the endpoint. **Default** `0.25`.
     */
    minCu?: pulumi.Input<number>;
    /**
     * Project the endpoint belongs to.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Suspend timeout of the endpoint. **Default** `0`.
     */
    suspendTimeout?: pulumi.Input<number>;
    /**
     * Type of the endpoint.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Endpoint resource.
 */
export interface EndpointArgs {
    /**
     * Branch the endpoint belongs to.
     */
    branchId: pulumi.Input<string>;
    /**
     * Maximum number of compute units for the endpoint. **Default** `0.25`.
     */
    maxCu?: pulumi.Input<number>;
    /**
     * Minimum number of compute units for the endpoint. **Default** `0.25`.
     */
    minCu?: pulumi.Input<number>;
    /**
     * Project the endpoint belongs to.
     */
    projectId: pulumi.Input<string>;
    /**
     * Suspend timeout of the endpoint. **Default** `0`.
     */
    suspendTimeout?: pulumi.Input<number>;
}
