// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectState, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'neon:index/project:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Primary branch settings of the project.
     */
    public readonly branch!: pulumi.Output<outputs.ProjectBranch>;
    /**
     * Name of the project.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Organization of the project.
     */
    public readonly orgId!: pulumi.Output<string | undefined>;
    /**
     * PostgreSQL version of the project. **Default** `15`.
     */
    public readonly pgVersion!: pulumi.Output<number>;
    /**
     * Platform of the project.
     */
    public /*out*/ readonly platformId!: pulumi.Output<string>;
    /**
     * Region of the project.
     */
    public readonly regionId!: pulumi.Output<string>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectArgs | ProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectState | undefined;
            resourceInputs["branch"] = state ? state.branch : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["orgId"] = state ? state.orgId : undefined;
            resourceInputs["pgVersion"] = state ? state.pgVersion : undefined;
            resourceInputs["platformId"] = state ? state.platformId : undefined;
            resourceInputs["regionId"] = state ? state.regionId : undefined;
        } else {
            const args = argsOrState as ProjectArgs | undefined;
            if ((!args || args.regionId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'regionId'");
            }
            resourceInputs["branch"] = args ? args.branch : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["orgId"] = args ? args.orgId : undefined;
            resourceInputs["pgVersion"] = args ? args.pgVersion : undefined;
            resourceInputs["regionId"] = args ? args.regionId : undefined;
            resourceInputs["platformId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Project.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Project resources.
 */
export interface ProjectState {
    /**
     * Primary branch settings of the project.
     */
    branch?: pulumi.Input<inputs.ProjectBranch>;
    /**
     * Name of the project.
     */
    name?: pulumi.Input<string>;
    /**
     * Organization of the project.
     */
    orgId?: pulumi.Input<string>;
    /**
     * PostgreSQL version of the project. **Default** `15`.
     */
    pgVersion?: pulumi.Input<number>;
    /**
     * Platform of the project.
     */
    platformId?: pulumi.Input<string>;
    /**
     * Region of the project.
     */
    regionId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Primary branch settings of the project.
     */
    branch?: pulumi.Input<inputs.ProjectBranch>;
    /**
     * Name of the project.
     */
    name?: pulumi.Input<string>;
    /**
     * Organization of the project.
     */
    orgId?: pulumi.Input<string>;
    /**
     * PostgreSQL version of the project. **Default** `15`.
     */
    pgVersion?: pulumi.Input<number>;
    /**
     * Region of the project.
     */
    regionId: pulumi.Input<string>;
}
